
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { _Sitecore } from "./_.Sitecore.Override"
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { ComponentRendering, RouteData, Field, ImageField, FileField, LinkField } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { DefaultComponentProps } from '@/lib/component-props';


export namespace Hackathon.Sitecore.templates.Hackathon.Header.Fields {
    export type Header = 
            Hackathon.Sitecore.templates.Hackathon.Base.Fields.title & { 
        fields?: { 
            /**
            * Represents the Header Logo field (406ceb15-233f-41b4-96e4-003e7bff4e42).
            */
            Logo: Field<string>;
 
        }
 }; 
}

export namespace Hackathon.Sitecore.templates.Hackathon.Base.Fields {
    export type title = { 
        fields?: { 
            /**
            * Represents the $name field (0a7d00f2-43aa-4951-a61f-e366050a7014).
            */
            title: Field<string>;
 
        }
 }; 
}


